<?php

namespace common\models;

use Yii;

/**
 * This is the model class for table "{{%anh_slider}}".
 *
 * @property int $id
 * @property string|null $file
 * @property int $slider_id
 *
 * @property Slider $slider
 */
class AnhSlider extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return '{{%anh_slider}}';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['slider_id'], 'required'],
            [['slider_id'], 'integer'],
            [['file'], 'string', 'max' => 100],
            [['slider_id'], 'exist', 'skipOnError' => true, 'targetClass' => Slider::className(), 'targetAttribute' => ['slider_id' => 'id']],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'file' => 'File',
            'slider_id' => 'Slider ID',
        ];
    }

    /**
     * Gets query for [[Slider]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getSlider()
    {
        return $this->hasOne(Slider::className(), ['id' => 'slider_id']);
    }

    public function afterDelete()
    {
        //đường dẫn hình ảnh slider trên ổ cứng
        $path = dirname(dirname(__DIR__)).'/images/'.$this->file;
        if(is_file($path))//kiểm tra có đúng là file ko
            unlink($path);//xóa file đó bằng hàm unlink
        parent::afterDelete(); // TODO: Change the autogenerated stub
    }
}
