<?php

namespace common\models;

use Yii;
use yii\db\Expression;
use yii\web\UploadedFile;

/**
 * This is the model class for table "{{%blog}}".
 *
 * @property int $id
 * @property string|null $tieu_de
 * @property string|null $mo_ta_ngan
 * @property string|null $noi_dung
 * @property string|null $ngay_dang
 * @property string|null $ngay_sua
 * @property int|null $nguoi_dang_id
 * @property int|null $nguoi_sua_id
 * @property string|null $anh_dai_dien
 *
 * @property User $nguoiDang
 * @property User $nguoiSua
 */
class Blog extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return '{{%blog}}';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['noi_dung'], 'string'],
            [['ngay_dang', 'ngay_sua'], 'safe'],
            [['nguoi_dang_id', 'nguoi_sua_id'], 'integer'],
            [['tieu_de', 'mo_ta_ngan', 'anh_dai_dien'], 'string', 'max' => 255],
            [['nguoi_dang_id'], 'exist', 'skipOnError' => true, 'targetClass' => User::className(), 'targetAttribute' => ['nguoi_dang_id' => 'id']],
            [['nguoi_sua_id'], 'exist', 'skipOnError' => true, 'targetClass' => User::className(), 'targetAttribute' => ['nguoi_sua_id' => 'id']],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'tieu_de' => 'Tieu De',
            'mo_ta_ngan' => 'Mo Ta Ngan',
            'noi_dung' => 'Noi Dung',
            'ngay_dang' => 'Ngay Dang',
            'ngay_sua' => 'Ngay Sua',
            'nguoi_dang_id' => 'Nguoi Dang ID',
            'nguoi_sua_id' => 'Nguoi Sua ID',
            'anh_dai_dien' => 'Anh Dai Dien',
        ];
    }

    /**
     * Gets query for [[NguoiDang]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getNguoiDang()
    {
        return $this->hasOne(User::className(), ['id' => 'nguoi_dang_id']);
    }

    /**
     * Gets query for [[NguoiSua]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getNguoiSua()
    {
        return $this->hasOne(User::className(), ['id' => 'nguoi_sua_id']);
    }

    public function beforeSave($insert)
    {
        if($insert){
            $this->ngay_dang = new Expression("NOW()");
            $this->nguoi_dang_id = 2;//Yii::$app->user->id;
        }
        else{
            $this->ngay_sua = new Expression("NOW()");
            $this->nguoi_dang_id = 2;
        }



        #region Upload file
        $file = UploadedFile::getInstance($this,'anh_dai_dien');
        if(!is_null($file)){
            $time = time();
            $type = $file->getExtension();

            $ten_file = API_H17::createCode($this->tieu_de);
            $ten_file = "{$time}_blog-{$ten_file}.{$type}";
            $this->anh_dai_dien = $ten_file;
            if(!$insert){
                //đoạn này là update a.jpg = b.jpg
                $blog = self::findOne($this->id);
                Yii::$app->session->set('old_name_logo', $blog->anh_dai_dien);
            }

        }else{//không upload file
            if($insert)
                $this->anh_dai_dien = 'no-image.jpeg';
            else{//trường hợp update
                //bước 1 lấy lại giá trị logo cũ
                $blog = self::findOne($this->id);
                //Bước 2 gán giá trị logo mới = logo cũ
                $this->anh_dai_dien = $blog->anh_dai_dien;
            }
        }
        #endregion
        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }

    function afterSave($insert, $changedAttributes)
    {
        #region Upload file ảnh đại diện
        //upload ảnh sau khi lưu dữ liệu vào csdl thành công
        $file = UploadedFile::getInstance($this,'anh_dai_dien');
        if(!is_null($file)){
            $ten_file = $this->anh_dai_dien;
            $path = dirname(dirname(__DIR__)).'/images/'.$ten_file;
            $file->saveAs($path);

            if(!$insert){
                $ten_file_cu =Yii::$app->session->get('old_name_logo');
                if($ten_file_cu!= 'no-image.jpeg'){
                    $path = dirname(dirname(__DIR__)).'/images/'.$ten_file_cu;
                    if(is_file($path))
                        unlink($path);
                }
            }
        }
        #endregion
        parent::afterSave($insert, $changedAttributes); // TODO: Change the autogenerated stub
    }

    function beforeDelete()
    {
        // trước khi xóa thì cần xóa ảnh trên thư mục images trước
        if($this->anh_dai_dien !='no-image.jpeg'){
            $path = dirname(dirname(__DIR__)).'/images/'.$this->anh_dai_dien;
            if(is_file($path))
                unlink($path);
        }
        return parent::beforeDelete(); // TODO: Change the autogenerated stub
    }
}
