<?php

namespace common\models;

use Yii;

/**
 * This is the model class for table "{{%don_hang_chi_tiet}}".
 *
 * @property int $id
 * @property int $don_hang_id
 * @property int $san_pham_id
 * @property int $so_luong
 * @property double $don_gia
 * @property double $gia_nhap
 * @property int $chiet_khau
 * @property string $kieu_chiet_khau
 * @property double $thanh_tien
 * @property double $tong_tien
 * @property int $ton_kho
 *
 * @property DonHang $donHang
 * @property SanPham $sanPham
 */
class DonHangChiTiet extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return '{{%don_hang_chi_tiet}}';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['don_hang_id', 'san_pham_id', 'so_luong', 'don_gia'], 'required'],
            [['don_hang_id', 'san_pham_id', 'so_luong'], 'integer'],
            [['don_gia','ton_kho'], 'number'],
            [['gia_nhap','chiet_khau','kieu_chiet_khau','tong_tien','thanh_tien'],'safe'],
            [['don_hang_id'], 'exist', 'skipOnError' => true, 'targetClass' => DonHang::className(), 'targetAttribute' => ['don_hang_id' => 'id']],
            [['san_pham_id'], 'exist', 'skipOnError' => true, 'targetClass' => SanPham::className(), 'targetAttribute' => ['san_pham_id' => 'id']],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'don_hang_id' => 'Don Hang ID',
            'san_pham_id' => 'San Pham ID',
            'so_luong' => 'So Luong',
            'don_gia' => 'Don Gia',
        ];
    }

    /**
     * Gets query for [[DonHang]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getDonHang()
    {
        return $this->hasOne(DonHang::className(), ['id' => 'don_hang_id']);
    }

    /**
     * Gets query for [[SanPham]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getSanPham()
    {
        return $this->hasOne(SanPham::className(), ['id' => 'san_pham_id']);
    }

    public function beforeSave($insert)
    {
        $this->thanh_tien = $this->so_luong * $this->don_gia;
        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }
}
