<?php

namespace common\models;
use Yii;
use yii\base\BaseObject;
use yii\db\Expression;

/**
 * This is the model class for table "{{%don_hang}}".
 *
 * @property int $id
 * @property string $ngay_dat
 * @property float $tong_tien
 * @property string $ho_ten
 * @property string $dien_thoai
 * @property string|null $email
 * @property string $dia_chi_giao_hang
 * @property string|null $ghi_chu
 * @property double $ship
 * @property double $vat
 * @property double $thanh_tien
 * @property double|null $chiet_khau
 * @property double|null $doanh_thu
 * @property string|null $kieu_chiet_khau
 * @property string $hinh_thuc_thanh_toan
 * @property string $tinh_trang
 * @property string|null $ly_do_huy
 * @property int|null $tong_so_luong
 * @property int|null $khach_hang_id
 * @property string|null $type
 * @property DonHangChiTiet[] $donHangChiTiets
 */

class DonHang extends \yii\db\ActiveRecord
{

    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return '{{%don_hang}}';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [[ 'ho_ten', 'dien_thoai', 'dia_chi_giao_hang'], 'required'],
            [['ngay_dat','khach_hang_id','type','doanh_thu'], 'safe'],
            [['tong_tien', 'ship', 'vat', 'thanh_tien', 'chiet_khau'], 'number'],
            [['kieu_chiet_khau', 'hinh_thuc_thanh_toan', 'tinh_trang'], 'string'],
            [['tong_so_luong'], 'integer'],
            [['ho_ten'], 'string', 'max' => 60],
            [['dien_thoai'], 'string', 'max' => 20],
            [['email'], 'string', 'max' => 100],
            [['dia_chi_giao_hang'], 'string', 'max' => 200],
            [['ghi_chu', 'ly_do_huy'], 'string', 'max' => 500],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'ngay_dat' => 'Ngay Dat',
            'tong_tien' => 'Tong Tien',
            'ho_ten' => 'Ho Ten',
            'dien_thoai' => 'Dien Thoai',
            'email' => 'Email',
            'dia_chi_giao_hang' => 'Dia Chi Giao Hang',
            'ghi_chu' => 'Ghi Chu',
            'ship' => 'Ship',
            'vat' => 'Vat',
            'thanh_tien' => 'Thanh Tien',
            'chiet_khau' => 'Chiet Khau',
            'kieu_chiet_khau' => 'Kieu Chiet Khau',
            'hinh_thuc_thanh_toan' => 'Hinh Thuc Thanh Toan',
            'tinh_trang' => 'Tinh Trang',
            'ly_do_huy' => 'Ly Do Huy',
            'tong_so_luong' => 'Tong So Luong',
        ];
    }

    /**
     * Gets query for [[DonHangChiTiets]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getDonHangChiTiets()
    {
        return $this->hasMany(DonHangChiTiet::className(), ['don_hang_id' => 'id']);
    }

    public function beforeSave($insert)
    {
        if($this->type=='Nhập hàng'){
            if($insert){
                $this->ngay_dat = new Expression('NOW()');
                $this->ship = 0;
                $this->vat = 0;
                $this->chiet_khau = 0;
                $this->kieu_chiet_khau = 'Phần trăm';
                $this->hinh_thuc_thanh_toan = 'Tiền mặt';
                $this->tinh_trang = '';
            }
        }else{
            if(!Yii::$app->user->isGuest)
                $this->khach_hang_id = Yii::$app->user->id;
            if($insert){
                $this->ngay_dat = new Expression('NOW()');
                $this->ship = 0;
                $this->vat=0;
                $this->chiet_khau=0;
                $this->kieu_chiet_khau='Phần trăm';
                $this->hinh_thuc_thanh_toan='Tiền mặt';
                $this->tinh_trang = 'Đang chờ xử lý';
            }
        }
        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }

    public function afterSave($insert, $changedAttributes)
    {
//        if($this->type != 'Nhập hàng'){
//            // Sửa đơn hàng
//            if(isset($_POST['soluong'])){
//                $thanh_tien = 0;//thành tiền thu phía khách hàng
//                $tong_sl = 0;
//
//                if($this->tinh_trang=='Đang giao hàng'){
//                    //Lấy ra các chi tiết đơn hàng tồn theo thứ tự tăng dần của ngày nhập đơn hàng
//                    //Ví dụ : DDH1 - ngày nhập 20/11 - chitietdonhang co số lượng tồn : 5,nhập 10,bán 20
//                    //Ví dụ : DDH2 - ngày nhập 22/11 - chitietdonhang co số lượng tồn : 15, nhập 15, bán 25
//                    //Ví dụ : DDH3 - ngày nhập 25/11 - chitietdonhang co số lượng tồn : 25, nhập 15, bán 25
//                    //Đặt 15, giá bán hiện tại = (20+25+25)/3 = 23k
//                    // 5 - 15 = -10 => Doanh thu = 5 * (23-10) = 5 * 13 = 65
//                    //15 - 10 = 5  => Doanh thu = 10 * (23-15) = 10 * 8 = 80
//                    $doanh_thu = 0;
//                    //xử lý update số lượng và tính doanh thu
//                    foreach ($_POST['soluong'] as $chitietdonhang_id => $sl){
//                        $tong_sl += $sl;
//                        $model_chitietdonhang = DonHangChiTiet::findOne($chitietdonhang_id);
//                        $sp = SanPham::findOne($model_chitietdonhang->san_pham_id);
//                        $thanh_tien += $sl * $sp->gia_ban;
//
//                        $ds_chitietdonhang =  QuanLyChiTietDonHang::find()
//                            ->andFilterWhere(['san_pham_id'=>$model_chitietdonhang->san_pham_id])
//                            ->andFilterWhere(['>','ton_kho',0])
//                            ->andFilterWhere(['type'=>'Nhập hàng'])
//                            ->orderBy(['ngay_dat'=>SORT_ASC])
//                            ->all();
//                        /** @var  QuanLyChiTietDonHang $item_chitietdonhang */
//                        //[0=>,1 => ,2 =>,3=?]
//                        $so_luong_dat = $sl;
//                        $i = 0;
//
//                        while($so_luong_dat > 0 ){
//                            $item_chitietdonhang = $ds_chitietdonhang[$i];
//                            $soluong_ton = $item_chitietdonhang->ton_kho;
//                            $soluong_ton = $soluong_ton - $so_luong_dat;// -10
//                            if($soluong_ton < 0)//0
//                            {
//                                $doanh_thu += $item_chitietdonhang->ton_kho * ($item_chitietdonhang->gia_ban - $item_chitietdonhang->gia_nhap);
//                                $so_luong_dat = abs($soluong_ton);
//                                $soluong_ton = 0;
//
//                            }
//                            else{
//                                $doanh_thu += $so_luong_dat * ($item_chitietdonhang->gia_ban - $item_chitietdonhang->gia_nhap);
//                                $so_luong_dat = 0;
//                            }
//
//                            $i++;
//                            DonHangChiTiet::updateAll(['ton_kho'=>$soluong_ton],['id'=>$item_chitietdonhang->id]);
//                        }
//                        SanPham::updateAll(['so_luong'=> $sp->so_luong - $sl],['id'=>$model_chitietdonhang->san_pham_id]);
//                    }
//                }
//                else if ($this->tinh_trang=='Hủy'){
//                    if($changedAttributes['tinh_trang']=='Đang giao hàng'){
//                        //Cộng số lượng đã hủy vào sản phẩm
//                    }
//                }
//                DonHang::updateAll(['doanh_thu'=>$doanh_thu,'thanh_tien'=>$thanh_tien,'tong_tien'=>$thanh_tien*(1-$this->chiet_khau/100),'tong_so_luong'=>$tong_sl],['id'=>$this->id]);
//        }else{
                if($insert){


                //Lưu đơn hàng mới
                $san_pham = Yii::$app->session['san_pham'];
                $so_luong=Yii::$app->session['so_luong'];
                $tong_tien=Yii::$app->session['da_dat_hang'];
                $so_luong_da_dat=Yii::$app->session['so_luong_da_dat'];
                /** @var SanPham $item */
                foreach ($san_pham as $item){
                    $chi_tiet_don_hang = new DonHangChiTiet();
                    $chi_tiet_don_hang->don_hang_id=$this->id;
                    $chi_tiet_don_hang->san_pham_id=$item->id;
                    $chi_tiet_don_hang->so_luong = $so_luong[$item->id];
                    $chi_tiet_don_hang->don_gia = $item->gia_ban;
                    $chi_tiet_don_hang->save();
                }
                DonHang::updateAll([
                    'tong_tien'=>$tong_tien,
                    'thanh_tien'=>$tong_tien,
                    'tong_so_luong'=>$so_luong_da_dat
                ],['id'=>$this->id]);
                }
//
//            }
//        }

        parent::afterSave($insert, $changedAttributes); // TODO: Change the autogenerated stub
    }

    public function getIconTinhTrang($tinh_trang){
        $TINH_TRANG = array(
            'Đang chờ xử lý'=>'<span class="text-warning"><i class="fa fa-refresh"></i> Đang chờ xử lý</span>',
            'Đang giao hàng'=>'<span class="text-primary"><i class="fa fa-truck"></i> Đang giao hàng</span>',
            'Đang xử lý'=>'<span class="text-warning"><i class="fa fa-refresh"> Đang xử lý</span>',
            'Đã giao hàng'=>'<span class="text-success"><i class="fa fa-check-circle-o"> Đã giao hàng</span>',
            'Chờ xác nhận hủy'=>'<span class="text-danger"><i class="fa fa-spinner"> Chờ xác nhận hủy</span>',
            'Hủy'=>'<span class="text-danger"><i class="fa fa-ban"> Đã hủy</span>'
        );
        return $TINH_TRANG[$tinh_trang];
    }
}
