<?php

namespace common\models;

use Yii;
use yii\helpers\VarDumper;
use yii\web\UploadedFile;

/**
 * This is the model class for table "{{%thuong_hieu}}".
 *
 * @property int $id
 * @property string $name Tên thương hiệu
 * @property string|null $code
 * @property string $logo
 *
 * @property SanPham[] $sanPhams
 */
class ThuongHieu extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return '{{%thuong_hieu}}';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['name'], 'required'],
            [['name', 'code'], 'string', 'max' => 45],
            [['logo'], 'string', 'max' => 100],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'name' => 'Tên thương hiệu',
            'code' => 'Code',
            'logo' => 'Logo',
        ];
    }

    /**
     * Gets query for [[SanPhams]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getSanPhams()
    {
        return $this->hasMany(SanPham::className(), ['thuong_hieu_id' => 'id']);
    }


    public function beforeSave($insert)
    {

        $this->code =  API_H17::createCode($this->name);

        //giả sử có file cũ : a.jpg
        //file mới : b.jpg
        //Các việc cần làm khi chọn 1 file mới thay cho file cũ
        // Xóa a.jpg => update a.jpg = b.jpg => upload b.jpg

        $file = UploadedFile::getInstance($this,'logo');
        if(!is_null($file)){
            $time = time();
            $type = $file->getExtension();

            $ten_file = API_H17::createCode($this->name);
            $ten_file = "{$time}_logo-{$ten_file}.{$type}";
            $this->logo = $ten_file;
            if(!$insert){
                //đoạn này là update a.jpg = b.jpg
                $thuonghieu = self::findOne($this->id);
                Yii::$app->session->set('old_name_logo', $thuonghieu->logo);
            }

        }else{//không upload file
            if($insert)
                $this->logo = 'no-image.jpeg';
            else{//trường hợp update
                //bước 1 lấy lại giá trị logo cũ
                $thuonghieu = self::findOne($this->id);
                //Bước 2 gán giá trị logo mới = logo cũ
                $this->logo = $thuonghieu->logo;
            }
        }
        //VarDumper::dump($file,10,true);
        //exit;
        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }

    public function afterSave($insert, $changedAttributes)
    {
        //upload ảnh sau khi lưu dữ liệu vào csdl thành công
        $file = UploadedFile::getInstance($this,'logo');
        if(!is_null($file)){
            $ten_file = $this->logo;
            $path = dirname(dirname(__DIR__)).'/images/'.$ten_file;
            $file->saveAs($path);

            if(!$insert){
                $ten_file_cu =Yii::$app->session->get('old_name_logo');
                if($ten_file_cu!= 'no-image.jpeg'){
                    $path = dirname(dirname(__DIR__)).'/images/'.$ten_file_cu;
                    if(is_file($path))
                        unlink($path);
                }
            }
        }
        parent::afterSave($insert, $changedAttributes); // TODO: Change the autogenerated stub
    }

    public function beforeDelete()
    {// trước khi xóa thì cần xóa ảnh trên thư mục images trước
        if($this->logo !='no-image.jpeg'){
            $path = dirname(dirname(__DIR__)).'/images/'.$this->logo;
            if(is_file($path))
                unlink($path);
        }
        return parent::beforeDelete(); // TODO: Change the autogenerated stub
    }
}
